-- ==========================================
-- HEY YOUTH! — Supabase Database Schema
-- ==========================================

-- 1. CMS & Website Content Tables

-- Testimonials
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL, -- 'internal' or 'external'
    name VARCHAR(255) NOT NULL,
    role_id VARCHAR(255), -- for internal
    role_en VARCHAR(255), -- for internal
    title_id VARCHAR(255), -- for external
    title_en VARCHAR(255), -- for external
    quote_id TEXT NOT NULL,
    quote_en TEXT NOT NULL,
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- FAQs
CREATE TABLE IF NOT EXISTS public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id TEXT NOT NULL,
    question_en TEXT NOT NULL,
    answer_id TEXT NOT NULL,
    answer_en TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Volunteer/Member Locations
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lat NUMERIC(9, 6) NOT NULL,
    lng NUMERIC(9, 6) NOT NULL,
    volunteers INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Partners
CREATE TABLE IF NOT EXISTS public.partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description_id TEXT NOT NULL,
    description_en TEXT NOT NULL,
    icon VARCHAR(100),
    image TEXT,
    color VARCHAR(50),
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Team Members
CREATE TABLE IF NOT EXISTS public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role_id VARCHAR(255) NOT NULL,
    role_en VARCHAR(255) NOT NULL,
    image TEXT,
    linkedin TEXT,
    instagram TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Activities / Blogs
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id VARCHAR(100) NOT NULL,
    category_en VARCHAR(100) NOT NULL,
    date_str VARCHAR(100) NOT NULL, -- e.g., '10 November 2025'
    title_id TEXT NOT NULL,
    title_en TEXT NOT NULL,
    description_id TEXT NOT NULL,
    description_en TEXT NOT NULL,
    image TEXT,
    link TEXT,
    full_story_id TEXT NOT NULL,
    full_story_en TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Podcasts
CREATE TABLE IF NOT EXISTS public.podcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id VARCHAR(100) NOT NULL,
    episode_en VARCHAR(100) NOT NULL,
    title_id TEXT NOT NULL,
    title_en TEXT NOT NULL,
    thumbnail TEXT,
    spotify_link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Donation Settings (Single-row Settings)
CREATE TABLE IF NOT EXISTS public.donation_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1), -- force single row
    hero_title_id TEXT NOT NULL,
    hero_title_en TEXT NOT NULL,
    hero_subtitle_id TEXT NOT NULL,
    hero_subtitle_en TEXT NOT NULL,
    strip_text_id TEXT NOT NULL,
    strip_text_en TEXT NOT NULL,
    strip_image TEXT,
    bank_name VARCHAR(100) NOT NULL,
    account_name VARCHAR(100) NOT NULL,
    account_number VARCHAR(100) NOT NULL,
    qris_image TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- About Hero Settings (Single-row Settings)
CREATE TABLE IF NOT EXISTS public.about_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1), -- force single row
    title_id TEXT NOT NULL,
    title_en TEXT NOT NULL,
    subtitle_id TEXT NOT NULL,
    subtitle_en TEXT NOT NULL,
    volunteer_count VARCHAR(50) NOT NULL,
    image TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- 2. Mentoring Program Tables

-- Mentoring Subject Categories
CREATE TABLE IF NOT EXISTS public.sd_categories (
    id VARCHAR(100) PRIMARY KEY, -- e.g., 'matematika', 'english'
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Mentoring Classes
CREATE TABLE IF NOT EXISTS public.teacher_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) REFERENCES public.sd_categories(id) ON UPDATE CASCADE,
    grade VARCHAR(100) NOT NULL, -- e.g., 'Kelas 4 - 6 SD'
    slot INTEGER NOT NULL DEFAULT 0,
    desc_text TEXT NOT NULL,
    date_str VARCHAR(100) NOT NULL, -- e.g., 'Sabtu, 28 Juli 2026'
    time_str VARCHAR(100) NOT NULL, -- e.g., '10:00 - 11:30 WIB'
    platform VARCHAR(150) NOT NULL,
    mentor VARCHAR(255) NOT NULL,
    mentor_title VARCHAR(255) NOT NULL,
    avatar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Mentoring Registrations
CREATE TABLE IF NOT EXISTS public.teacher_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(255) NOT NULL,
    grade VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    notes TEXT,
    class_title VARCHAR(255) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- 3. Event & Certificate Tables

-- Event Registrations & Certificate Lookups
CREATE TABLE IF NOT EXISTS public.event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    event_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    instansi VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    domisili VARCHAR(255),
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- Enable Row Level Security (RLS) for all tables
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.podcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donation_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sd_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;

-- Create Policies (Select: Public, Write: Authenticated users only)
-- Note: Adjust policy rules depending on whether you want anyone to write or just admins.

-- Testimonials Public Select
DROP POLICY IF EXISTS "Allow public select on testimonials" ON public.testimonials;
CREATE POLICY "Allow public select on testimonials" ON public.testimonials FOR SELECT USING (true);

-- FAQs Public Select
DROP POLICY IF EXISTS "Allow public select on faqs" ON public.faqs;
CREATE POLICY "Allow public select on faqs" ON public.faqs FOR SELECT USING (true);

-- Locations Public Select
DROP POLICY IF EXISTS "Allow public select on locations" ON public.locations;
CREATE POLICY "Allow public select on locations" ON public.locations FOR SELECT USING (true);

-- Partners Public Select
DROP POLICY IF EXISTS "Allow public select on partners" ON public.partners;
CREATE POLICY "Allow public select on partners" ON public.partners FOR SELECT USING (true);

-- Team Members Public Select
DROP POLICY IF EXISTS "Allow public select on team_members" ON public.team_members;
CREATE POLICY "Allow public select on team_members" ON public.team_members FOR SELECT USING (true);

-- Activities Public Select
DROP POLICY IF EXISTS "Allow public select on activities" ON public.activities;
CREATE POLICY "Allow public select on activities" ON public.activities FOR SELECT USING (true);

-- Podcasts Public Select
DROP POLICY IF EXISTS "Allow public select on podcasts" ON public.podcasts;
CREATE POLICY "Allow public select on podcasts" ON public.podcasts FOR SELECT USING (true);

-- Donation Settings Public Select
DROP POLICY IF EXISTS "Allow public select on donation_settings" ON public.donation_settings;
CREATE POLICY "Allow public select on donation_settings" ON public.donation_settings FOR SELECT USING (true);

-- About Settings Public Select
DROP POLICY IF EXISTS "Allow public select on about_settings" ON public.about_settings;
CREATE POLICY "Allow public select on about_settings" ON public.about_settings FOR SELECT USING (true);

-- Mentoring Categories Public Select
DROP POLICY IF EXISTS "Allow public select on sd_categories" ON public.sd_categories;
CREATE POLICY "Allow public select on sd_categories" ON public.sd_categories FOR SELECT USING (true);

-- Mentoring Classes Public Select
DROP POLICY IF EXISTS "Allow public select on teacher_classes" ON public.teacher_classes;
CREATE POLICY "Allow public select on teacher_classes" ON public.teacher_classes FOR SELECT USING (true);


-- Event Registrations (Public Insert, Authenticated Select/Update/Delete)
DROP POLICY IF EXISTS "Allow public insert on event_registrations" ON public.event_registrations;
CREATE POLICY "Allow public insert on event_registrations" ON public.event_registrations FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin operations on event_registrations" ON public.event_registrations;
CREATE POLICY "Allow admin operations on event_registrations" ON public.event_registrations FOR ALL TO authenticated USING (true);


-- Mentoring Registrations (Public Insert, Authenticated Select/Update/Delete)
DROP POLICY IF EXISTS "Allow public insert on teacher_registrations" ON public.teacher_registrations;
CREATE POLICY "Allow public insert on teacher_registrations" ON public.teacher_registrations FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin operations on teacher_registrations" ON public.teacher_registrations;
CREATE POLICY "Allow admin operations on teacher_registrations" ON public.teacher_registrations FOR ALL TO authenticated USING (true);


-- Admin CRUD for all master data
DROP POLICY IF EXISTS "Allow admin write operations on testimonials" ON public.testimonials;
CREATE POLICY "Allow admin write operations on testimonials" ON public.testimonials FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on faqs" ON public.faqs;
CREATE POLICY "Allow admin write operations on faqs" ON public.faqs FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on locations" ON public.locations;
CREATE POLICY "Allow admin write operations on locations" ON public.locations FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on partners" ON public.partners;
CREATE POLICY "Allow admin write operations on partners" ON public.partners FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on team_members" ON public.team_members;
CREATE POLICY "Allow admin write operations on team_members" ON public.team_members FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on activities" ON public.activities;
CREATE POLICY "Allow admin write operations on activities" ON public.activities FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on podcasts" ON public.podcasts;
CREATE POLICY "Allow admin write operations on podcasts" ON public.podcasts FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on donation_settings" ON public.donation_settings;
CREATE POLICY "Allow admin write operations on donation_settings" ON public.donation_settings FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on about_settings" ON public.about_settings;
CREATE POLICY "Allow admin write operations on about_settings" ON public.about_settings FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on sd_categories" ON public.sd_categories;
CREATE POLICY "Allow admin write operations on sd_categories" ON public.sd_categories FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write operations on teacher_classes" ON public.teacher_classes;
CREATE POLICY "Allow admin write operations on teacher_classes" ON public.teacher_classes FOR ALL TO authenticated USING (true);


-- 4. Initial Seed Data

-- Initial Mentoring Categories
INSERT INTO public.sd_categories (id, name) VALUES
('matematika', 'Matematika'),
('english', 'Bahasa Inggris'),
('sains', 'IPA & Sains')
ON CONFLICT (id) DO NOTHING;

-- Initial Settings
INSERT INTO public.donation_settings (id, hero_title_id, hero_title_en, hero_subtitle_id, hero_subtitle_en, strip_text_id, strip_text_en, strip_image, bank_name, account_name, account_number, qris_image) VALUES
(1, 'Dukung Misi Kami', 'Support Our Mission', 'Bantu kami menyediakan akses pendidikan yang layak bagi anak-anak Indonesia. Setiap donasi Anda menjadi jembatan menuju masa depan yang lebih cerah.', 'Help us provide decent access to education for Indonesian children. Every donation you make is a bridge to a brighter future.', 'Bersama Kita Bisa', 'Together We Can', 'img/Front Card.webp', 'Bank Central Asia (BCA)', 'Yuni Triandini', '466 0070 724', 'https://via.placeholder.com/200?text=QRIS')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.about_settings (id, title_id, title_en, subtitle_id, subtitle_en, volunteer_count, image) VALUES
(1, 'Mendidik Untuk <br><span class="text-primary">Masa Depan Indonesia</span>', 'Educating For <br><span class="text-primary">Indonesia''s Future</span>', 'Hey Youth adalah sebuah komunitas pemuda di Indonesia yang didedikasikan untuk melakukan perubahan melalui pendidikan. Kami menyediakan akses ke pendidikan berkualitas dan peluang mentoring bagi mereka yang membutuhkan.', 'Hey Youth is a youth community in Indonesia dedicated to making changes through education. We provide access to quality education and mentoring opportunities for those in need.', '1k+', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=2070&auto=format&fit=crop')
ON CONFLICT (id) DO NOTHING;
