-- ==========================================
-- HEY YOUTH! — Supabase Database Schema Patch
-- ==========================================

-- Certificates Table
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_number VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    event_name VARCHAR(255) NOT NULL,
    issue_date VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL DEFAULT 'Participant',
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for Certificates
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- Create Policies for Certificates
DROP POLICY IF EXISTS "Allow public select on certificates" ON public.certificates;
CREATE POLICY "Allow public select on certificates" ON public.certificates FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin operations on certificates" ON public.certificates;
CREATE POLICY "Allow admin operations on certificates" ON public.certificates FOR ALL TO authenticated USING (true);

-- Insert Mock/Seed Certificate Data
INSERT INTO public.certificates (certificate_number, name, email, phone, event_name, issue_date, role, description) VALUES
('HY-DS26-0001', 'Budi Santoso', 'peserta@heyyouth.org', '08123456789', 'HeyYouth Digital Summit 2026', '18 Juli 2026', 'Participant', 'as a **Participant** in the online webinar **HeyYouth Digital Summit 2026**'),
('HY-DS26-0002', 'Jane Doe', 'speaker@heyyouth.org', '08987654321', 'HeyYouth Digital Summit 2026', '18 Juli 2026', 'Speaker', 'as a **Speaker** in the online webinar **HeyYouth Digital Summit 2026**'),
('HY-REG-014838', 'Henri Prasetyo', 'henriprasetyo6@gmail.com', '081122334455', 'Hey Youth Summit 2026', 'July 22nd - 23rd, 2026', 'Participant', 'in recognition of your active participation in the **Hey Youth: Future Ready Summit** themed **"What Makes You Irreplaceable in the AI Era."**')
ON CONFLICT (certificate_number) DO NOTHING;
