-- =======================================================
-- HEY YOUTH! — Supabase Layout & Events Database Schema Patch
-- =======================================================

-- 1. Events Table (To hold dynamic event data)
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id VARCHAR(255) NOT NULL,
    title_en VARCHAR(255),
    date VARCHAR(100) NOT NULL,
    time VARCHAR(100),
    location VARCHAR(255),
    description_id TEXT,
    description_en TEXT,
    speaker VARCHAR(255),
    speaker_role VARCHAR(255),
    image TEXT,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for Events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Events Policies
DROP POLICY IF EXISTS "Allow public select on events" ON public.events;
CREATE POLICY "Allow public select on events" ON public.events FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin all on events" ON public.events;
CREATE POLICY "Allow admin all on events" ON public.events FOR ALL TO authenticated USING (true);

-- Seed initial event if not exists
INSERT INTO public.events (title_id, title_en, date, time, location, description_id, description_en, speaker, speaker_role, image, link)
VALUES (
    'Webinar Persiapan Karir Global',
    'Global Career Preparation Webinar',
    '25 Juli 2026',
    '15:00 WIB',
    'Zoom Meeting',
    'Webinar gratis untuk membantu mahasiswa mempersiapkan karir di tingkat global.',
    'Free webinar to help students prepare for global careers.',
    'Yuni Triandini',
    'Founder of Hey Youth',
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1000&auto=format&fit=crop',
    'https://zoom.us/j/123456789'
) ON CONFLICT DO NOTHING;


-- 2. Certificate Settings Table (Re-creation supporting multiple events)
DROP TABLE IF EXISTS public.certificate_settings CASCADE;

CREATE TABLE public.certificate_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(255) UNIQUE NOT NULL,
    template_image TEXT,
    layout_json JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.certificate_settings ENABLE ROW LEVEL SECURITY;

-- Policies for Certificate Settings
DROP POLICY IF EXISTS "Allow public select on certificate_settings" ON public.certificate_settings;
CREATE POLICY "Allow public select on certificate_settings" ON public.certificate_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin all on certificate_settings" ON public.certificate_settings;
CREATE POLICY "Allow admin all on certificate_settings" ON public.certificate_settings FOR ALL TO authenticated USING (true);

-- Insert default fallback layout (using a special default name)
INSERT INTO public.certificate_settings (event_name, template_image, layout_json)
VALUES ('-- DEFAULT LAYOUT --', null, null)
ON CONFLICT (event_name) DO NOTHING;
